### ISSUE TITLE
自定义构建

### ISSUE THREAD

**Issue by nkeonkeo** [zdhxiong/mdui#237]
如何自定义构建？

不需要用到各种主题色，不需要用到js中的功能

1.0.0版本没有无法自定义构建这个功能？

似乎是在`src/index.less`中修改, 希望作者写个大致说明

**Comment by nkeonkeo** [comment]
似乎构建后只得到了css，并没有得到js和其他文件

**Comment by zdhxiong** [comment]
index.less 和 index.ts 文件里，不要的组件自己删掉

**Comment by nkeonkeo** [comment]
> index.less 和 index.ts 文件里，不要的组件自己删掉

可不可以说一下`gulpfile.js`中mdui.js构建函数怎么写?

**Comment by zdhxiong** [comment]
> 可不可以说一下`gulpfile.js`中mdui.js构建函数怎么写?

npm run build

**Comment by nkeonkeo** [comment]
`npm run js`时错误如下:

```bash
Found 264 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mdui@1.0.0 js: `npm run eslint && tsc -p src/tsconfig.json && rollup --config`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the mdui@1.0.0 js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zcmimi/.npm/_logs/2020-10-09T04_32_37_420Z-debug.log
```

` /home/zcmimi/.npm/_logs/2020-10-09T04_32_37_420Z-debug.log`内容如下:

```log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'js' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prejs', 'js', 'postjs' ]
5 info lifecycle mdui@1.0.0~prejs: mdui@1.0.0
6 info lifecycle mdui@1.0.0~js: mdui@1.0.0
7 verbose lifecycle mdui@1.0.0~js: unsafe-perm in lifecycle true
8 verbose lifecycle mdui@1.0.0~js: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/zcmimi/mdui/node_modules/.bin:/home/zcmimi/.vscode-server/bin/e5e9e69aed6e1984f7499b7af85b3d05f9a6883a/bin:/home/zcmimi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/nodejs/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Users/zcmimi/AppData/Local/Programs/Python/Python38/Scripts/:/mnt/c/Users/zcmimi/AppData/Local/Programs/Python/Python38/:/mnt/c/Users/zcmimi/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/Bandizip/:/mnt/c/Users/zcmimi/AppData/Roaming/npm:/mnt/c/MinGW/bin:/mnt/c/Program Files (x86)/GitHub CLI/:/snap/bin
9 verbose lifecycle mdui@1.0.0~js: CWD: /home/zcmimi/mdui
10 silly lifecycle mdui@1.0.0~js: Args: [ '-c',
10 silly lifecycle   'npm run eslint && tsc -p src/tsconfig.json && rollup --config' ]
11 silly lifecycle mdui@1.0.0~js: Returned: code: 2  signal: null
12 info lifecycle mdui@1.0.0~js: Failed to exec js script
13 verbose stack Error: mdui@1.0.0 js: `npm run eslint && tsc -p src/tsconfig.json && rollup --config`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid mdui@1.0.0
15 verbose cwd /home/zcmimi/mdui
16 verbose Linux 4.4.0-18362-Microsoft
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "js"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 2
22 error mdui@1.0.0 js: `npm run eslint && tsc -p src/tsconfig.json && rollup --config`
22 error Exit status 2
23 error Failed at the mdui@1.0.0 js script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by zdhxiong** [comment]
node 升级到 12 以上

**Comment by nkeonkeo** [comment]
`node v12.19.0`还是不行啊

**Comment by nkeonkeo** [comment]
```log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'js' ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose run-script [ 'prejs', 'js', 'postjs' ]
5 info lifecycle mdui@1.0.0~prejs: mdui@1.0.0
6 info lifecycle mdui@1.0.0~js: mdui@1.0.0
7 verbose lifecycle mdui@1.0.0~js: unsafe-perm in lifecycle true
8 verbose lifecycle mdui@1.0.0~js: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/zcmimi/mdui/node_modules/.bin:/home/zcmimi/.vscode-server/bin/e5e9e69aed6e1984f7499b7af85b3d05f9a6883a/bin:/home/zcmimi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/nodejs/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Users/zcmimi/AppData/Local/Programs/Python/Python38/Scripts/:/mnt/c/Users/zcmimi/AppData/Local/Programs/Python/Python38/:/mnt/c/Users/zcmimi/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/Bandizip/:/mnt/c/Users/zcmimi/AppData/Roaming/npm:/mnt/c/MinGW/bin:/mnt/c/Program Files (x86)/GitHub CLI/:/snap/bin
9 verbose lifecycle mdui@1.0.0~js: CWD: /home/zcmimi/mdui
10 silly lifecycle mdui@1.0.0~js: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'npm run eslint && tsc -p src/tsconfig.json && rollup --config'
10 silly lifecycle ]
11 silly lifecycle mdui@1.0.0~js: Returned: code: 2  signal: null
12 info lifecycle mdui@1.0.0~js: Failed to exec js script
13 verbose stack Error: mdui@1.0.0 js: `npm run eslint && tsc -p src/tsconfig.json && rollup --config`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid mdui@1.0.0
15 verbose cwd /home/zcmimi/mdui
16 verbose Linux 4.4.0-18362-Microsoft
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "js"
18 verbose node v12.19.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 2
22 error mdui@1.0.0 js: `npm run eslint && tsc -p src/tsconfig.json && rollup --config`
22 error Exit status 2
23 error Failed at the mdui@1.0.0 js script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by zdhxiong** [comment]
自己想想办法吧, 我不想回答了
